CREATE TABLE CART (
ID INT IDENTITY(1,1) PRIMARY KEY,
user_id VARCHAR(100) NOT NULL REFERENCES USERDB(id),
product_id VARCHAR(100) NOT NULL REFERENCES PRODUCTS(id),
quantity INT NOT NULL,
order_date DATETIME DEFAULT GETDATE()
);