CREATE TABLE cart(
    id VARCHAR(255) PRIMARY KEY,
    product_id VARCHAR(200) FOREIGN KEY REFERENCES product(id) NOT NULL,
    user_id VARCHAR(200) FOREIGN KEY REFERENCES users(id) NOT NULL,
    quantity INT DEFAULT 0,
    isDeleted INT DEFAULT 0
)

