-- CREATE TABLE ORDERS (
-- ID INT IDENTITY(1,1) PRIMARY KEY,
-- user_id VARCHAR(100) NOT NULL,
-- product_id VARCHAR(100) NOT NULL REFERENCES PRODUCTS(id),
-- quantity INT NOT NULL,
-- price DECIMAL(10, 2) NOT NULL,
-- order_date DATETIME DEFAULT GETDATE()
-- FOREIGN KEY (user_id) REFERENCES USERDB (id)
-- );
CREATE TABLE ORDERS (
    id INT IDENTITY(1, 1) PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    product_id VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    total AS (quantity * price) PERSISTED,
    order_date DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (user_id) REFERENCES USERDB (id),
    FOREIGN KEY (product_id) REFERENCES PRODUCTS (id)
);

